spring:
  application:
    name: soportedesk-backend
  profiles:
    active: dev
  sql:
    init:
      mode: never
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:c29wb3J0ZWRlc2staW5pYS1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWNjaW9uLTEyMzQ1Ng==}
  expiration-ms: 86400000

licencia:
  encryption-key: ${LICENCIA_ENCRYPTION_KEY:CBkkF72fkRZoZLynAdKy0wLsBqZJx2AycpfPEE+9+8o=}

agente:
  inventario-token: ${AGENTE_INVENTARIO_TOKEN:change-me-agent-token}

uploads:
  drivers-dir: uploads/drivers

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:sqlserver://172.16.26.16:1433;databaseName=ssti;encrypt=false;trustServerCertificate=true
    username: sa
    password: $Lipknot86
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
